### ISSUE TITLE
Copyrights of lecture notes

### ISSUE THREAD

**Issue by InnerPeace-Wu** [berkeleydeeprlcourse/homework#13]
Thx for the amazing work.
For now, I am personally writing lecture notes based on cs294-fall2017 course. And I am doing this for clearing my thoughts of some ideas and math. Besides, I am planning to open source it ([here is the repo](https://github.com/InnerPeace-Wu/cs294-Fall17-notes)), but I don't know if there is any copyright issues I should aware of, or do you think it's appropriate?

**Comment by cbfinn** [comment]
Yes, that's fine to open-source your notes.

Chelsea
