### ISSUE TITLE
HW1 Setup

### ISSUE THREAD

**Issue by mahiuchun** [berkeleydeeprlcourse/homework#17]
I encountered two issues when trying to follow the setup instruction for HW1.

1. Latest version of [mujoco-py](https://github.com/openai/mujoco-py) wants MuJoCo 1.50 rather than MuJoCo 1.31.
2. `XXX-v1` environment is no longer available from latest version of [gym](https://github.com/openai/gym); I had to use `XXX-v2` instead.

**Comment by rddy** [comment]
Should be fixed in the Fall 2018 version of HW1.
