### ISSUE TITLE
`gym.benchmark_spec` no longer valid

### ISSUE THREAD

**Issue by smdsbz** [berkeleydeeprlcourse/homework#18]
Got `AttributeError: module 'gym' has no attribute 'benchmark_spec'` thrown from [this line](https://github.com/berkeleydeeprlcourse/homework/blob/60b3ef08c2dca3961efb63b32683bb588571f226/hw3/run_dqn_atari.py#L121).  

`gym` no longer have this experimental feature, manually setting `env = gym.make(game_name)` and `max_timestep` as mentioned from [here](https://github.com/openai/gym/commit/c6215f190d9242985c4e7184c36aab8dd99883f9#diff-170d6bbf20fa02890840c39b9fbb66a0L164) as workaround.

**Comment by rddy** [comment]
Thanks for pointing this out. We'll fix it in the Fall 2018 version of HW3.
