### ISSUE TITLE
I cannot find tensorflow 1.10.5

### ISSUE THREAD

**Issue by cww97** [berkeleydeeprlcourse/homework#31]
When I use `conda search`

I can find version `1.10.0` , `1.11.0`..., I dont know if it may matter if I choose version `1.10.0`.

Or, Where could I find version `1.10.5`.

Sorry I am a newer for `tf`

**Comment by PabTorre** [comment]
would be nice to just setup a dockerFile and avoid all these setup issues... 

(been struggling with mujoco_py myself for the last couple of days)

**Comment by cww97** [comment]
thx
