### ISSUE TITLE
[README] Mujoco Requirement

### ISSUE THREAD

**Issue by Carmezim** [berkeleydeeprlcourse/homework#6]
Hi folks, first of all, thanks for the amazing material and work you open sourced, outstanding and generous gift to the community.

I wondered if would be interesting to add a side note regarding Mujoco 1.3 on recent Macs.
This version didn't support NVMe disks and still an [open issue](https://github.com/openai/gym/issues/638) where there are more details regarding it.

**Comment by cbfinn** [comment]
Sure. Feel free to make a pull request for the README.

**Comment by Carmezim** [comment]
As soon as https://github.com/openai/gym/pull/767 is merged we could remove the note for Mac users and update the dependencies to MuJoCo v1.5, if it's of your interest.

I tested those changes on an NVMe Mac and it works.
